# Workflow for building and deploying a Jekyll site to GitHub Pages
name: Build & Deploy Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Data
        run: cp ./russian-losses.json ./docs/_data/russian-losses.json

      - name: Copy Assets
        run: |
          mkdir -p ./docs/assets
          cp ./russian-losses.json ./docs/assets/russian-losses.json
          cp -r ./schema/ ./docs/assets/
          ls -r ./docs/assets

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: docs
          destination: _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
