name: Losses Pull Request Review

on:
  pull_request:

jobs:
  verify-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure Cache
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: verify-json-npm-${{ runner.os }}

    - name: Prepare Schema Validation
      run: npm install -g ajv-cli

    - name: Run Value Validation
      run: node .github/workflows/pr-loss-auto-check/index.js

    - name: Run Schema Validation
      run: >
        ajv validate -s schema/russian-losses.en.schema.json -d russian-losses.json --strict=false --spec=draft2020
        ajv validate -s schema/pertes-russes.fr.schema.json -d russian-losses.json --strict=false --spec=draft2020
        ajv validate -s schema/russische-verluste.de.schema.json -d russian-losses.json --strict=false --spec=draft2020
        ajv validate -s schema/втрати-росії.uk.schema.json -d russian-losses.json --strict=false --spec=draft2020
        ajv validate -s schema/потери-россии.ru.schema.json -d russian-losses.json --strict=false --spec=draft2020
